//!
//! This module is for character/enemy stat type definitions
//!

use crate::prelude::*;

// stat-related submodules
mod autoload;
mod battler;
mod charmap;
mod enemy;
mod pchars;
mod savefiles;
mod statcalc;

// re-export some crap from ^^^
pub use autoload::StatsInterface;
pub use battler::{Battler, Battlers};
pub use charmap::CharMap;
pub use enemy::EnemyData;
pub use pchars::{EnemyID, PChar};
pub use savefiles::SaveFile;
pub use statcalc::{CharStatCalcs, StatCalcFn, StatCalcList};

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct BattleStats {
    pub hp: IntegralStat,
    pub mana: Option<IntegralStat>,
    pub energy: IntegralStat,
    pub buffs: Vec<InherentStats>,
}

/// All the information the game needs to know about a character
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CharData {
    pub id: String,

    /// Name of the character, as picked by the user
    /// ⚠️⚠️⚠️ See <https://github.com/Lamby777/PETS-G/issues/23>
    pub display_name: String,

    pub level: IntegralStat,
    pub inherent_stats: InherentStats,
    pub battle_stats: BattleStats,

    /// Status effects the character has
    pub status_effects: HashSet<StatusEffect>,

    /// Items this character is holding
    pub inventory: Vec<Item>,

    /// Equipment this character is wearing/using
    ///
    /// # Important
    ///
    /// Equipping an item REMOVES it from the inventory!
    ///
    /// Not only does that make it easier to code, but it
    /// also prevents feeling that your inventory space is
    /// being "wasted" by equipment.
    pub equipment: Vec<Item>,
}

impl Battler for CharData {
    fn id(&self) -> String {
        self.id.clone()
    }

    fn hp_mut(&mut self) -> &mut IntegralStat {
        &mut self.battle_stats.hp
    }

    fn status_effects(&self) -> &HashSet<StatusEffect> {
        &self.status_effects
    }

    fn status_effects_mut(&mut self) -> &mut HashSet<StatusEffect> {
        &mut self.status_effects
    }

    fn inherent_stats(&self) -> &InherentStats {
        &self.inherent_stats
    }

    fn equipment(&self) -> &[Item] {
        &self.equipment
    }

    fn buffs_list(&self) -> &[InherentStats] {
        &self.battle_stats.buffs
    }
}

/// Stats that are inherent to a character or enemy type.
///
/// This doesn't mean they never change; they do every
/// time you level up or use certain items...
///
/// It just means "inherent" as in it doesn't constantly
/// change like HP, mana, or energy.
#[derive(
    Clone,
    Debug,
    Default,
    Eq,
    Hash,
    PartialEq,
    derive_more::Sum,
    Serialize,
    Deserialize
)]
pub struct InherentStats {
    pub max_hp: IntegralStat,
    pub max_energy: IntegralStat,

    pub attack: IntegralStat,
    pub defense: IntegralStat,
    pub speed: IntegralStat,
    pub stability: IntegralStat, // PK defense

    // refer to google doc for what these do...
    // can't pick a good name for em yet
    pub delta: IntegralStat,   // "the crit one"
    pub epsilon: IntegralStat, // "the combo one"

    // Exclusive to certain characters
    // Spoiler alert: Ethan is not the only one who needs lambda... :>
    pub lambda: Option<IntegralStat>,
    pub max_mana: Option<IntegralStat>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StatusEffect {
    /// Can't move, but recover 20% energy on wakeup
    Sleeping,

    /// ^^^ No movement, no energy recovery, but still has PK. Almost no combos
    Paralyzed,

    /// Oops, all your attacks missed! Sowwy :<
    Crying,

    /// Like uncontrollable crying + also no PK, but lower miss rate overall
    LightHeaded,

    /// No attacks, painfully slow movement
    ShortBreath,

    /// "Disoriented", auditory flashbang + harder combos
    Dizzy,

    /// Battle board turns black
    Blinded,

    /// Damage over time
    Burning,

    /// More damage over time, introduced later in the game
    Frostbite,

    /// ^^^ HP meter biased towards rolling down faster
    Bleeding,

    /// ^^^ no PK
    Poison,

    /// ^^^ no PK, completely unable to fight (basically dead)
    PoisonR,

    /// Less lenient music timing.
    Tired,
}

impl Display for StatusEffect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        use StatusEffect::*;

        let s = match self {
            LightHeaded => "Light-headed",
            ShortBreath => "Short of breath",
            Burning => "On Fire",
            PoisonR => "Poisoned (R)",
            _ => return Debug::fmt(&self, f),
        };

        write!(f, "{}", s)
    }
}

// WARNING: The stuff below is mostly just boilerplate garbage generated by copilot.

impl Default for CharData {
    fn default() -> Self {
        CharData {
            id: PChar::DEVON.to_owned(),
            display_name: "Chicken Nugget".to_owned(),
            level: 1,

            // i seriously can't `..Default::default()` because
            // that would be infinite recursion... WTF?
            inherent_stats: Default::default(),
            battle_stats: Default::default(),
            status_effects: Default::default(),
            inventory: Default::default(),
            equipment: Default::default(),
        }
    }
}

impl std::ops::Add for InherentStats {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        InherentStats {
            max_hp: self.max_hp + rhs.max_hp,
            max_energy: self.max_energy + rhs.max_energy,
            attack: self.attack + rhs.attack,
            defense: self.defense + rhs.defense,
            speed: self.speed + rhs.speed,
            stability: self.stability + rhs.stability,
            delta: self.delta + rhs.delta,
            epsilon: self.epsilon + rhs.epsilon,

            lambda: self.lambda.zip(rhs.lambda).map(|(a, b)| a + b),
            max_mana: self.max_mana.zip(rhs.max_mana).map(|(a, b)| a + b),
        }
    }
}

impl std::ops::Sub for InherentStats {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self {
        InherentStats {
            max_hp: self.max_hp - rhs.max_hp,
            max_energy: self.max_energy - rhs.max_energy,
            attack: self.attack - rhs.attack,
            defense: self.defense - rhs.defense,
            speed: self.speed - rhs.speed,
            stability: self.stability - rhs.stability,
            delta: self.delta - rhs.delta,
            epsilon: self.epsilon - rhs.epsilon,

            lambda: self.lambda.zip(rhs.lambda).map(|(a, b)| a - b),
            max_mana: self.max_mana.zip(rhs.max_mana).map(|(a, b)| a - b),
        }
    }
}
