# pub struct Item {
#     /// The category of the item. This affects how you can use it in-game.
#     category: ItemCat,
#
#     /// Things that describe what the item does or is
#     ///
#     /// This may be used for weaknesses/resistances, sorting purposes,
#     /// shopkeeper price calculations, etc.
#     attributes: Vec<ItemAttribute>,
#
#     name: String,
#     description: String,
# }

